#ifndef SPRITES_DEFS_H
#define SPRITES_DEFS_H

#include <stdint.h>

typedef struct {
  const char *data;
  uint8_t width;
  uint8_t height;
} t_sprite;

typedef enum {
  SPRITE_SIMPLE_WOODEN_LEG,
  SPRITE_SIMPLE_WOODEN_BACK,
  SPRITE_SIMPLE_WOODEN_SEAT,

  SPRITE_CUSHIONED_SEAT,
  SPRITE_CUSHIONED_BACK,
  SPRITE_UPHOLSTERED_BACK,
  SPRITE_UPHOLSTERED_SEAT,

  SPRITE_STURDY_WOODEN_LEG,
  SPRITE_STURDY_TOP_PLATE,

  SPRITE_OFFICE_WOODEN_LEG,
  SPRITE_OFFICE_HARD_SEAT,
  SPRITE_OFFICE_HARD_BACK,
  SPRITE_OFFICE_CUSHION_SEAT,
  SPRITE_OFFICE_CUSHION_BACK,
  SPRITE_OFFICE_UPHOLSTERY,

  SPRITE_ARTISTIC_FRAME_LEFT,
  SPRITE_ARTISTIC_FRAME_RIGHT,
  SPRITE_ARTISTIC_HEADBOARD,
  SPRITE_ARTISTIC_FOOTBOARD,
  SPRITE_ARTISTIC_BASE_BOARD,
  SPRITE_ARTISTIC_CARVED_DECORATION,

  SPRITE_CHILD_LEG,
  SPRITE_CHILD_SEAT,
  SPRITE_CHILD_BACK,
  SPRITE_CHILD_CORNER_GUARD,

  SPRITE_ELEGANT_LEG,
  SPRITE_ELEGANT_SEAT,
  SPRITE_ELEGANT_BACK,
  SPRITE_ELEGANT_ARMREST,

  SPRITE_MAGIC_LEG,
  SPRITE_MAGIC_SEAT,
  SPRITE_MAGIC_BACK,
  SPRITE_MAGIC_CARVED_DETAIL,

  SPRITE_CAT_FLOOR,
  SPRITE_CAT_WALL_LEFT,
  SPRITE_CAT_WALL_RIGHT,
  SPRITE_CAT_WALL_BACK,
  SPRITE_CAT_ROOF,
  SPRITE_CAT_WINDOW,

  SPRITE_CANOPIED_FRAME_LEFT,
  SPRITE_CANOPIED_FRAME_RIGHT,
  SPRITE_CANOPIED_HEADBOARD,
  SPRITE_CANOPIED_FOOTBOARD,
  SPRITE_CANOPIED_BASE_BOARD,
  SPRITE_CANOPIED_VERTICAL_SUPPORT,
  SPRITE_CANOPIED_CANOPY,

  
  NUM_SPRITES
} t_sprite_id;

extern const t_sprite sprites[NUM_SPRITES];

#endif //SPRITES_DEFS_H
