#ifndef SPRITES_DEFS_H
#define SPRITES_DEFS_H

#include <stdint.h>

typedef struct {
  const char *data;
  uint8_t width;
  uint8_t height;
} t_sprite;

typedef enum {

// Части мебели  
  SPRITE_SIMPLE_WOODEN_LEG,
  SPRITE_SIMPLE_WOODEN_BACK,
  SPRITE_SIMPLE_WOODEN_SEAT,

  SPRITE_CUSHIONED_SEAT,
  SPRITE_CUSHIONED_BACK,
  SPRITE_UPHOLSTERED_BACK,
  SPRITE_UPHOLSTERED_SEAT,

  SPRITE_STURDY_WOODEN_LEG,
  SPRITE_STURDY_TOP_PLATE,

  SPRITE_OFFICE_WOODEN_LEG,
  SPRITE_OFFICE_HARD_SEAT,
  SPRITE_OFFICE_HARD_BACK,
  SPRITE_OFFICE_CUSHION_SEAT,
  SPRITE_OFFICE_CUSHION_BACK,
  SPRITE_OFFICE_UPHOLSTERY,

  SPRITE_ARTISTIC_FRAME_LEFT,
  SPRITE_ARTISTIC_FRAME_RIGHT,
  SPRITE_ARTISTIC_HEADBOARD,
  SPRITE_ARTISTIC_FOOTBOARD,
  SPRITE_ARTISTIC_BASE_BOARD,
  SPRITE_ARTISTIC_CARVED_DECORATION,

  SPRITE_CHILD_LEG,
  SPRITE_CHILD_SEAT,
  SPRITE_CHILD_BACK,
  SPRITE_CHILD_CORNER_GUARD,

  SPRITE_ELEGANT_LEG,
  SPRITE_ELEGANT_SEAT,
  SPRITE_ELEGANT_BACK,
  SPRITE_ELEGANT_ARMREST,

  SPRITE_MAGIC_LEG,
  SPRITE_MAGIC_SEAT,
  SPRITE_MAGIC_BACK,
  SPRITE_MAGIC_CARVED_DETAIL,

  SPRITE_CAT_FLOOR,
  SPRITE_CAT_WALL_LEFT,
  SPRITE_CAT_WALL_RIGHT,
  SPRITE_CAT_WALL_BACK,
  SPRITE_CAT_ROOF,
  SPRITE_CAT_WINDOW,

  SPRITE_CANOPIED_FRAME_LEFT,
  SPRITE_CANOPIED_FRAME_RIGHT,
  SPRITE_CANOPIED_HEADBOARD,
  SPRITE_CANOPIED_FOOTBOARD,
  SPRITE_CANOPIED_BASE_BOARD,
  SPRITE_CANOPIED_VERTICAL_SUPPORT,
  SPRITE_CANOPIED_CANOPY,

// Бакграунды  
  SPRITE_BG_OUTDOOR,
  SPRITE_BG_HOME,
  SPRITE_BG_SHORE,
  SPRITE_BG_OFFICE,
  SPRITE_BG_STUDIO,
  SPRITE_BG_KITCHEN,
  SPRITE_BG_PARLOUR,
  SPRITE_BG_DRAWING_ROOM,
  SPRITE_BG_CASTLE,
  
// Одежда
  SPRITE_CLOTH_WORK_JACKET,
  SPRITE_CLOTH_DRESS,
  SPRITE_CLOTH_SAILOR_COAT,
  SPRITE_CLOTH_SUIT,
  SPRITE_CLOTH_PAINTED_SHIRT,
  SPRITE_CLOTH_TSHIRT,
  SPRITE_CLOTH_SHAWL,
  SPRITE_CLOTH_ENGINEER_JACKET,
  SPRITE_CLOTH_ROBE,

// Лицо
  SPRITE_NOSE1,
  SPRITE_NOSE2,
  SPRITE_NOSE3,
  SPRITE_MOUTH1,
  SPRITE_MOUTH2,
  SPRITE_MOUTH3,
  SPRITE_EYES1,
  SPRITE_EYES2,
  SPRITE_EYES3,
  SPRITE_HAIR1,
  SPRITE_HAIR2,
  SPRITE_HAIR3,
  
  NUM_SPRITES
} t_sprite_id;

extern const t_sprite sprites[NUM_SPRITES];

#endif //SPRITES_DEFS_H
